import type { ThemeDef } from './types';

// 11 themes: 深夜(dark default), 月光(light default), + 9 light tinted
export const THEMES: ThemeDef[] = [
  {
    id: 'midnight',
    name: '深夜',
    vars: {
      '--bg': '#141414',
      '--bg-soft': '#1c1c1c',
      '--bg-elev': '#242424',
      '--surface': '#1f1f1f',
      '--surface-strong': '#262626',
      '--border': '#2a2a2a',
      '--text': '#e8e8e8',
      '--text-dim': '#9a9a9a',
      '--text-faint': '#5a5a5a',
      '--accent': '#e0e0e0',
      '--accent-2': '#666666',
      '--icon-bg': '#282828',
      '--icon-bg-active': '#333333',
      '--icon-color': '#d4d4d4',
      '--icon-line': '#c8c8c8',
      '--border-icon': '#353535',
      '--dock-bg': '#252525',
      '--wallpaper': 'linear-gradient(160deg,#1a1a1a 0%,#0e0e0e 100%)',
      '--danger': '#e06c6c',
      '--success': '#7fb079',
      '--warn': '#d4a85a',
    },
  },
  {
    id: 'daylight',
    name: '月光',
    vars: {
      '--bg': '#f5f5f5',
      '--bg-soft': '#eeeeee',
      '--bg-elev': '#e8e8e8',
      '--surface': '#e5e5e5',
      '--surface-strong': '#dfdfdf',
      '--border': '#d8d8d8',
      '--text': '#1a1a1a',
      '--text-dim': '#555555',
      '--text-faint': '#aaaaaa',
      '--accent': '#333333',
      '--accent-2': '#888888',
      '--icon-bg': '#e0e0e0',
      '--icon-bg-active': '#d5d5d5',
      '--icon-color': '#6a6a6a',
      '--icon-line': '#787878',
      '--border-icon': '#d0d0d0',
      '--dock-bg': '#e3e3e3',
      '--wallpaper': 'linear-gradient(160deg,#f5f5f5 0%,#eaeaea 100%)',
      '--danger': '#c0392b',
      '--success': '#27ae60',
      '--warn': '#d4a85a',
    },
  },
  {
    id: 'mist',
    name: '薄雾',
    vars: {
      '--bg': '#f2f4f6',
      '--bg-soft': '#eaedf0',
      '--bg-elev': '#e2e7eb',
      '--surface': '#e8ebef',
      '--surface-strong': '#dde2e7',
      '--border': '#dce0e5',
      '--text': '#1e2530',
      '--text-dim': '#5a6880',
      '--text-faint': '#a0aab8',
      '--accent': '#3a5070',
      '--accent-2': '#7090b0',
      '--icon-bg': '#dce1e6',
      '--icon-bg-active': '#cfd6dd',
      '--icon-color': '#5a7898',
      '--dock-bg': '#e0e5ea',
      '--wallpaper': 'linear-gradient(160deg,#edf0f5 0%,#e0e6ec 100%)',
      '--danger': '#c0392b',
      '--success': '#27ae60',
      '--warn': '#d4a85a',
    },
  },
  {
    id: 'dawn',
    name: '晨露',
    vars: {
      '--bg': '#f2f5f2',
      '--bg-soft': '#eaf0ea',
      '--bg-elev': '#e2ebe2',
      '--surface': '#e8efe8',
      '--surface-strong': '#dde6dd',
      '--border': '#dce3dc',
      '--text': '#1e2b1e',
      '--text-dim': '#4a684a',
      '--text-faint': '#90a890',
      '--accent': '#2e5c30',
      '--accent-2': '#6a9a6c',
      '--icon-bg': '#dce2dc',
      '--icon-bg-active': '#cfd7cf',
      '--icon-color': '#3d6b3f',
      '--dock-bg': '#e0e5e0',
      '--wallpaper': 'linear-gradient(160deg,#edf5ee 0%,#e0ede2 100%)',
      '--danger': '#c0392b',
      '--success': '#27ae60',
      '--warn': '#d4a85a',
    },
  },
  {
    id: 'sakura',
    name: '樱花',
    vars: {
      '--bg': '#f6f2f4',
      '--bg-soft': '#f0e8ec',
      '--bg-elev': '#ecdfe6',
      '--surface': '#eee5e9',
      '--surface-strong': '#e5d9df',
      '--border': '#e3d8dd',
      '--text': '#2e1a22',
      '--text-dim': '#7a3a52',
      '--text-faint': '#c094a8',
      '--accent': '#7a2848',
      '--accent-2': '#c07090',
      '--icon-bg': '#e3d7dc',
      '--icon-bg-active': '#d7c8cf',
      '--icon-color': '#7a2e4e',
      '--dock-bg': '#e6dce1',
      '--wallpaper': 'linear-gradient(160deg,#f5eff3 0%,#ece4ea 100%)',
      '--danger': '#c0392b',
      '--success': '#27ae60',
      '--warn': '#d4a85a',
    },
  },
  {
    id: 'sky',
    name: '天青',
    vars: {
      '--bg': '#f0f5f6',
      '--bg-soft': '#e6f0f2',
      '--bg-elev': '#daeaee',
      '--surface': '#e4ecef',
      '--surface-strong': '#d8e3e7',
      '--border': '#d6e2e6',
      '--text': '#0e2830',
      '--text-dim': '#306080',
      '--text-faint': '#80aac0',
      '--accent': '#145c78',
      '--accent-2': '#4a90b0',
      '--icon-bg': '#d6e2e6',
      '--icon-bg-active': '#c9d8dd',
      '--icon-color': '#1a5a76',
      '--dock-bg': '#dae5e9',
      '--wallpaper': 'linear-gradient(160deg,#e8f4f7 0%,#daeaee 100%)',
      '--danger': '#c0392b',
      '--success': '#27ae60',
      '--warn': '#d4a85a',
    },
  },
  {
    id: 'sand',
    name: '暖沙',
    vars: {
      '--bg': '#f6f3ee',
      '--bg-soft': '#f0eae0',
      '--bg-elev': '#ebe1d2',
      '--surface': '#e9e3d8',
      '--surface-strong': '#e0d8ca',
      '--border': '#ded6c8',
      '--text': '#2a1e0c',
      '--text-dim': '#6a5030',
      '--text-faint': '#b09070',
      '--accent': '#5a3810',
      '--accent-2': '#a07040',
      '--icon-bg': '#ddd5c7',
      '--icon-bg-active': '#d0c6b5',
      '--icon-color': '#5a3812',
      '--dock-bg': '#e1d9cc',
      '--wallpaper': 'linear-gradient(160deg,#f4f0e8 0%,#ede4d4 100%)',
      '--danger': '#c0392b',
      '--success': '#27ae60',
      '--warn': '#d4a85a',
    },
  },
  {
    id: 'gold',
    name: '浅金',
    vars: {
      '--bg': '#f6f4ee',
      '--bg-soft': '#f0ecde',
      '--bg-elev': '#ebe4ce',
      '--surface': '#e9e4d4',
      '--surface-strong': '#e0dac6',
      '--border': '#ded8c4',
      '--text': '#2a2408',
      '--text-dim': '#706020',
      '--text-faint': '#b8a060',
      '--accent': '#5c4c08',
      '--accent-2': '#a89030',
      '--icon-bg': '#ddd7c3',
      '--icon-bg-active': '#d0c8af',
      '--icon-color': '#5a4a0a',
      '--dock-bg': '#e1dbc8',
      '--wallpaper': 'linear-gradient(160deg,#f4f0e4 0%,#eae4cc 100%)',
      '--danger': '#c0392b',
      '--success': '#27ae60',
      '--warn': '#d4a85a',
    },
  },
  {
    id: 'lavender',
    name: '薰衣草',
    vars: {
      '--bg': '#f4f2f8',
      '--bg-soft': '#ece8f4',
      '--bg-elev': '#e4deee',
      '--surface': '#eae6f0',
      '--surface-strong': '#e0dae7',
      '--border': '#ded8e5',
      '--text': '#20102e',
      '--text-dim': '#60408a',
      '--text-faint': '#a888cc',
      '--accent': '#3e1870',
      '--accent-2': '#8860b8',
      '--icon-bg': '#ddd6e5',
      '--icon-bg-active': '#d0c6d8',
      '--icon-color': '#4a2080',
      '--dock-bg': '#e1dce8',
      '--wallpaper': 'linear-gradient(160deg,#f0ecf8 0%,#e6dff4 100%)',
      '--danger': '#c0392b',
      '--success': '#27ae60',
      '--warn': '#d4a85a',
    },
  },
  {
    id: 'frost',
    name: '霜蓝',
    vars: {
      '--bg': '#f0f4f8',
      '--bg-soft': '#e6eef6',
      '--bg-elev': '#dce8f2',
      '--surface': '#e2eaf0',
      '--surface-strong': '#d6e0e8',
      '--border': '#d4dee6',
      '--text': '#0c1e38',
      '--text-dim': '#3050a0',
      '--text-faint': '#7090cc',
      '--accent': '#0c2878',
      '--accent-2': '#4068c0',
      '--icon-bg': '#d3dde5',
      '--icon-bg-active': '#c5d0da',
      '--icon-color': '#143888',
      '--dock-bg': '#d7e1ea',
      '--wallpaper': 'linear-gradient(160deg,#eaf0f8 0%,#dce8f4 100%)',
      '--danger': '#c0392b',
      '--success': '#27ae60',
      '--warn': '#d4a85a',
    },
  },
  {
    id: 'bamboo',
    name: '竹影',
    vars: {
      '--bg': '#f2f6f2',
      '--bg-soft': '#e8f0e8',
      '--bg-elev': '#deeade',
      '--surface': '#e4ede4',
      '--surface-strong': '#d8e3d8',
      '--border': '#d6e1d6',
      '--text': '#102010',
      '--text-dim': '#306030',
      '--text-faint': '#70a070',
      '--accent': '#1a5020',
      '--accent-2': '#508850',
      '--icon-bg': '#d5e0d5',
      '--icon-bg-active': '#c7d4c7',
      '--icon-color': '#1a4a1e',
      '--dock-bg': '#d9e4d9',
      '--wallpaper': 'linear-gradient(160deg,#ecf4ec 0%,#deeade 100%)',
      '--danger': '#c0392b',
      '--success': '#27ae60',
      '--warn': '#d4a85a',
    },
  },
  // 新增淡色渐变主题
  {
    id: 'sunset',
    name: '日落渐变',
    vars: {
      '--bg': '#fef8f5',
      '--bg-soft': '#fef2ec',
      '--bg-elev': '#fdeae0',
      '--surface': '#f4ebe6',
      '--surface-strong': '#eeded6',
      '--border': '#ecdcd4',
      '--text': '#3a1810',
      '--text-dim': '#8a5040',
      '--text-faint': '#d0a090',
      '--accent': '#d45020',
      '--accent-2': '#ff8c5c',
      '--icon-bg': '#f0e0d8',
      '--icon-bg-active': '#e6d0c4',
      '--icon-color': '#c0502a',
      '--dock-bg': '#f0e2da',
      '--wallpaper': 'linear-gradient(160deg, #fff5f0 0%, #ffe8dc 40%, #ffd8c8 100%)',
      '--danger': '#c0392b',
      '--success': '#27ae60',
      '--warn': '#d4a85a',
    },
  },
  {
    id: 'ocean',
    name: '海洋渐变',
    vars: {
      '--bg': '#f5fbfe',
      '--bg-soft': '#ecf6fc',
      '--bg-elev': '#e0f0f8',
      '--surface': '#e6eef4',
      '--surface-strong': '#d8e4ed',
      '--border': '#d6e2eb',
      '--text': '#0a2838',
      '--text-dim': '#2a5878',
      '--text-faint': '#80b0d8',
      '--accent': '#1a68a0',
      '--accent-2': '#4098d8',
      '--icon-bg': '#d4e1ea',
      '--icon-bg-active': '#c4d4e0',
      '--icon-color': '#1a5c90',
      '--dock-bg': '#d8e4ed',
      '--wallpaper': 'linear-gradient(160deg, #f0f8ff 0%, #e0f0fc 40%, #d0e8f8 100%)',
      '--danger': '#c0392b',
      '--success': '#27ae60',
      '--warn': '#d4a85a',
    },
  },
  {
    id: 'rose',
    name: '玫瑰渐变',
    vars: {
      '--bg': '#fef5f8',
      '--bg-soft': '#fcecf2',
      '--bg-elev': '#f8e0ea',
      '--surface': '#f3e8ec',
      '--surface-strong': '#ebdae0',
      '--border': '#e9d8de',
      '--text': '#380818',
      '--text-dim': '#88385c',
      '--text-faint': '#d088a8',
      '--accent': '#b02858',
      '--accent-2': '#e86098',
      '--icon-bg': '#e8d5db',
      '--icon-bg-active': '#dcc4cc',
      '--icon-color': '#a02a52',
      '--dock-bg': '#ebdce1',
      '--wallpaper': 'linear-gradient(160deg, #fff0f5 0%, #ffe8f0 40%, #ffd8e8 100%)',
      '--danger': '#c0392b',
      '--success': '#27ae60',
      '--warn': '#d4a85a',
    },
  },
  {
    id: 'mint',
    name: '薄荷渐变',
    vars: {
      '--bg': '#f5fef8',
      '--bg-soft': '#ecfcf0',
      '--bg-elev': '#e0f8e8',
      '--surface': '#e6f1eb',
      '--surface-strong': '#d8e9e0',
      '--border': '#d6e7de',
      '--text': '#082818',
      '--text-dim': '#286848',
      '--text-faint': '#80c8a8',
      '--accent': '#188850',
      '--accent-2': '#40c888',
      '--icon-bg': '#d4e5dc',
      '--icon-bg-active': '#c4d8ce',
      '--icon-color': '#1a7a48',
      '--dock-bg': '#d8e9e1',
      '--wallpaper': 'linear-gradient(160deg, #f0fff5 0%, #e8fcf0 40%, #d8f8e8 100%)',
      '--danger': '#c0392b',
      '--success': '#27ae60',
      '--warn': '#d4a85a',
    },
  },
  {
    id: 'peach',
    name: '蜜桃渐变',
    vars: {
      '--bg': '#fffaf5',
      '--bg-soft': '#fff4ec',
      '--bg-elev': '#ffece0',
      '--surface': '#f5ede7',
      '--surface-strong': '#ede2d8',
      '--border': '#ebe0d6',
      '--text': '#3a2010',
      '--text-dim': '#8a6040',
      '--text-faint': '#d0b090',
      '--accent': '#d07030',
      '--accent-2': '#ffaa70',
      '--icon-bg': '#eadecf',
      '--icon-bg-active': '#deceba',
      '--icon-color': '#c0602a',
      '--dock-bg': '#ede3da',
      '--wallpaper': 'linear-gradient(160deg, #fffaf5 0%, #fff0e8 40%, #ffe8d8 100%)',
      '--danger': '#c0392b',
      '--success': '#27ae60',
      '--warn': '#d4a85a',
    },
  },
  {
    id: 'dream',
    name: '梦幻渐变',
    vars: {
      '--bg': '#f8f5fe',
      '--bg-soft': '#f2ecfc',
      '--bg-elev': '#eae0f8',
      '--surface': '#ede8f3',
      '--surface-strong': '#e2d8eb',
      '--border': '#e0d6e9',
      '--text': '#28082a',
      '--text-dim': '#68387a',
      '--text-faint': '#b888d0',
      '--accent': '#7828a0',
      '--accent-2': '#b860e8',
      '--icon-bg': '#ddd4e7',
      '--icon-bg-active': '#d0c4d8',
      '--icon-color': '#6a2892',
      '--dock-bg': '#e1d8ea',
      '--wallpaper': 'linear-gradient(160deg, #faf5ff 0%, #f2e8fc 40%, #e8d8f8 100%)',
      '--danger': '#c0392b',
      '--success': '#27ae60',
      '--warn': '#d4a85a',
    },
  },
  {
    id: 'cloud',
    name: '云雾渐变',
    vars: {
      '--bg': '#fafcfe',
      '--bg-soft': '#f4f8fc',
      '--bg-elev': '#ecf2f8',
      '--surface': '#ebeef2',
      '--surface-strong': '#e0e4ea',
      '--border': '#dee2e8',
      '--text': '#1a2838',
      '--text-dim': '#4a5868',
      '--text-faint': '#9aaac0',
      '--accent': '#3a5878',
      '--accent-2': '#6a90b8',
      '--icon-bg': '#dce0e6',
      '--icon-bg-active': '#ced2da',
      '--icon-color': '#3a5080',
      '--dock-bg': '#e0e4ea',
      '--wallpaper': 'linear-gradient(160deg, #fcfeff 0%, #f4f8fc 40%, #ecf2f8 100%)',
      '--danger': '#c0392b',
      '--success': '#27ae60',
      '--warn': '#d4a85a',
    },
  },
];

export function applyTheme(themeId: string) {
  const t = THEMES.find((x) => x.id === themeId) ?? THEMES[0];
  const root = document.documentElement;
  Object.entries(t.vars).forEach(([k, v]) => root.style.setProperty(k, v));
  // set body bg to match
  document.body.style.background = t.vars['--bg'] ?? '#141414';
}

export function isDark(themeId: string) {
  return themeId === 'midnight';
}
